### ISSUE TITLE
`camunda/implementation` fails for an element template

### ISSUE THREAD

**Issue by barmac** [camunda/bpmnlint-plugin-camunda#28]
Error is thrown:

```
App.js:944 rule <camunda/implementation> failed with error:  TypeError: extensionElements.some is not a function
    at hasConnector (implementation.js:63:1)
    at check (implementation.js:27:1)
    at r.enter (test-rule.js:70:30)
    at e (traverse.js:13:33)
    at traverse.js:29:13
    at Array.forEach (<anonymous>)
    at traverse.js:28:25
    at Array.forEach (<anonymous>)
    at e (traverse.js:23:25)
    at traverse.js:29:13
```

For the following template:

```json
[
  {
    "$schema": "https://unpkg.com/@camunda/element-templates-json-schema/resources/schema.json",
    "id": "create_order",
    "name": "Create Order",
    "description": "Create a new order to work with",
    "appliesTo": ["bpmn:ServiceTask"],
    "properties": [
      {
        "label": "Label1",
        "type": "String",
        "value": "value1",
        "binding": {
          "type": "camunda:field",
          "name": "Label1"
        }
      },
      {
        "label": "Label2",
        "type": "String",
        "value": "value2",
        "binding": {
          "type": "camunda:field",
          "name": "Label2"
        }
      },
      {
        "label": "Receivers",
        "type": "Hidden",
        "binding": {
          "type": "camunda:inputParameter",
          "name": "receivers"
        }
      }
    ]
  }
]
```

**Comment by nikku** [comment]
@barmac Thanks for opening the report. Could you share the diagram that fails to validate? The linter plugin operates not on element templates, but on BPMN diagrams.

**Comment by barmac** [comment]
Certainly! Below is the diagram:

[implementation.bpmn.txt](https://github.com/camunda/bpmnlint-plugin-camunda/files/14632902/implementation.bpmn.txt)

**Comment by barmac** [comment]
This is a duplicate of https://github.com/camunda/bpmnlint-plugin-camunda/issues/24 which was fixed a year ago via https://github.com/camunda/bpmnlint-plugin-camunda/pull/25 🙈

**Comment by barmac** [comment]
I had this due to out of date https://github.com/jonathanlukas/camunda-modeler-linter-default-rules on my machine. Sorry for wasting your time.
